### ISSUE TITLE
`acorn offerings computeclass` should only list computeclasses  support for the region.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#1426]
acorn version v0.6.0-106-g09f636a2+09f636a2
Steps to reproduce the problem:

1. Create a cluster scoped compute class without any supportedRegions - `cc1`
2. `acorn offerings computeclass` to list compute class.
compute class created in step1 gets listed.
3. Deploying an app with this computeclass fails with error -
  ✗  ERROR:  App.api.acorn.io "testcc" is invalid: computeclass: Invalid value: "": computeclass cc1 does not support region 

In this case , acorn offerings computeclass should not have listed  compute class - cc1 .

Note - Once "local" was added to supportedRegions , app deployment succeeded.

There needs to be support for listing all computeclass specific to a region.

Also should we not allow for creating compute class without any supportedRegions ?

**Comment by thedadams** [comment]
Cluster compute and volume classes show up regardless of the project when using `acorn offerings`. This is because they aren't tied to any project. Project compute and volume classes should work as you are expecting here.

It is my opinion that this is working as expected because cluster compute classes aren't tied to a specific project. They are global. Attempting to use a cluster compute class that your current project doesn't support should return an error, as expected.

Currently, we don't do any filtering anywhere based on project supported regions, especially in `runtime` where regions are used extensively. I am curious if others think that should change in this way.
