### ISSUE TITLE
auto-upgrade not outputted as part of acorn run -o yaml

### ISSUE THREAD

**Issue by cjellick** [acorn-io/runtime#1459]

**Comment by tylerslaton** [comment]
Gave this a look and this isn't a direct result of adding `-o`, `auto-upgrade` actually something that isn't set on the spec unless explicitly specified by the user. The daemon for `auto-upgrade` then makes assumptions based on what subset of those values are present.

For example, if you run an app without the `-o`, it will also have the `auto-upgrade` spec value not set but you will still get auto-upgrades. So the options I see are:
1. Move the daemon's "assumption" logic into `run.go` so that all apps that will be ran with `auto-upgrade` will have that field set regardless if it is explicitly set by the user.
2. Leave it the same and have consumers of `-o` yaml do that "assumption" logic.

For reference what I'm calling the "assumption logic" can be found [here](https://github.com/acorn-io/acorn/blob/487206457a1157a90ae4ac95224cdcdbe1b9adb1/pkg/autoupgrade/daemon.go#L330-L331).

Thoughts @cjellick?

**Comment by cjellick** [comment]
Pretty sure I want to change this behavior. I think this also affects the UI. Like, @vincent99 may not know to mark an app as autoupgrade if that flag isnt set.

I think the behavior I want is that the autoUpgrade field *must* be set, but the CLI helps - if the tag is detected to be a pattern, set the autoUpgrade field for the user. This should be done client side, not server side.

**Comment by tylerslaton** [comment]
The backend code for this has been set in place. Now the UI just needs to read from `AppInstance.Status.ObservedAutoUpgrade` in order to properly display when auto-upgrade is enabled.
