### ISSUE TITLE
Not able to use images that were built in 0.7.1 after upgrading to 0.8.0-rc5

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#2133]
**Version** -  `0.7.1` upgraded to `0.8.0-rc5`

**Steps to reproduce the problem:**
1. Install acorn version `v0.7.1+df5bf694`
2. Build an image  - `acorn  build -t mytest1:v1 .`
3. Deploy app using this image -  `acorn run -n testnew mytest1:v`
4. Install acorn version  `v0.8.0-rc5+15fc5478`
5. Deploy app using the image built in step2.

App deployment fails with `ERROR:  images.api.acorn.io "mytest1:v1" not found`

Image look up also fails  with `✗  ERROR:  images.api.acorn.io "mytest1:v1" not found`
```
 % acorn images                         
REPOSITORY   TAG       IMAGE-ID
mytest1      v1        21b06c2f3835

% acorn run -n afterupgrade mytest1:v1  
  ✗  ERROR:  images.api.acorn.io "mytest1:v1" not found

 % acorn run -n afterupgrade 21b06c2f3835
  ✗  ERROR:  images.api.acorn.io "21b06c2f3835" not found

% acorn image details mytest1:v1 
  ✗  ERROR:  images.api.acorn.io "mytest1:v1" not found

 % acorn image details 21b06c2f3835
  ✗  ERROR:  images.api.acorn.io "21b06c2f3835" not found

```

**Note** - We are also not able to stop apps that were deployed from Acornfile or deployed from a local image . These are apps that were deployed in 0.7.1 and we are not able to stop them after upgrade to 0.8.0-rc5.

```
acorn stop testnew
  ✗  ERROR:  stopping testnew: App.api.acorn.io "testnew" is invalid: spec.image: Invalid value: "mytest1:v1": images.api.acorn.io "21b06c2f3835072ae7b6874bdfbf45d68f2153e7178205ed34226c92762ce1ad" not found
```

**Comment by thedadams** [comment]
At some point, we changed the volume in the local registry of `runtime` from an `emptyDir` to a persistent volume. This means that any image that exists in `v0.7.1` will not exist when updating to `v0.8.0` because the volume the registry was using is overwritten by a persistent volume.

This will have to be release-noted for the upcoming release. A full migration from the `emptyDir` volume to the persistent one would be daunting. Additionally, deleting all images is not safe because a user could be upgrading from a version where this is not an issue.

**Comment by cjellick** [comment]
Nothing to retest on this, but will move to QA for visibility for @sangee2004

**Comment by sangee2004** [comment]
This has been documented in `Known Issues and Considerations` in Release notes:
```Because we've change the in-cluster registry to be backed by a peristent volume, existing images will be lost on upgrade. You should publish any "local" acorn images to an external registry such as ghcr.io.```
